DELIMITER \\
create trigger verifyAnsatInsert
BEFORE Insert
	ON ansat FOR EACH ROW
BEGIN 
	IF NEW.titel NOT BETWEEN 0 AND 3 THEN
		SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'Titel er ugyldig';
    ELSEIF CHAR_LENGTH(NEW.cpr) < 10 THEN
		SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'CPR nummeret er for kort';
	ELSEIF CHAR_LENGTH(NEW.cpr) > 10 THEN
		SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'CPR nummeret er for langt';
	ELSEIF NEW.titel NOT BETWEEN 0 AND 3 THEN
		SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'Titel er ugyldig';
	ELSEIF CHAR_LENGTH(NEW.ini) < 2 THEN
		SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'INI er for kort';
    END IF;
END \\
DELIMITER ;


DROP TRIGGER IF EXISTS verifyAnsatUpdate
DELIMITER \\
create trigger verifyAnsatUpdate
BEFORE UPDATE
	ON ansat FOR EACH ROW
BEGIN
	IF NEW.titel NOT BETWEEN 0 AND 3 THEN
		SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'Titel er ugyldig';
    ELSEIF CHAR_LENGTH(NEW.ini) < 2 THEN
		SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'INI er for kort';
	END IF;
END \\
DELIMITER ;