DELIMITER \\
create trigger verifyCPRInsert
BEFORE INSERT
	ON ansat FOR EACH ROW
BEGIN
	IF CHAR_LENGTH(NEW.cpr) < 10 THEN
		SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'CPR nummeret er for kort';
	ELSEIF CHAR_LENGTH(NEW.cpr) > 10 THEN
		SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'CPR nummeret er for langt';
	END IF;
END\\
DELIMITER ;

DELIMITER \\
create trigger verifyINIInsert
BEFORE INSERT
	ON ansat FOR EACH ROW
BEGIN
	IF CHAR_LENGTH(NEW.ini) < 2 THEN
		SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'INI er for kort';
	END IF;
END\\
DELIMITER ;

DELIMITER \\
create trigger verifyINIUpdate
BEFORE UPDATE
	ON ansat FOR EACH ROW
BEGIN
	IF CHAR_LENGTH(NEW.ini) < 2 THEN
		SIGNAL SQLSTATE '50000' SET MESSAGE_TEXT = 'INI er for kort';
	END IF;
END\\
DELIMITER ;

